import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages } from "next-intl/server";

import { LanguageSwitcher } from "@/components/language-switcher";
import { TRPCReactProvider } from "@/trpc/react";
import "./globals.css";

export const metadata: Metadata = {
  title: "OpenNext Cloudflare Starter Template",
  description: "Generated by OpenNext Cloudflare Starter Template",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <head>
        <link rel="icon" href="/favicon.svg" type="image/svg+xml"></link>
      </head>
      <body className="antialiased">
        <NextIntlClientProvider locale={locale} messages={messages}>
          <TRPCReactProvider>
            <LanguageSwitcher />
            {children}
          </TRPCReactProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
